import { Vehicle } from "@/app/types";

export const data: Vehicle[] = [
    {
      vehicleRegNo: 'T 123 ABC',
      group: 'Transport',
      status: 'en route',
      model: 'Toyota Hiace',
      healthRate: 85,
      costPerMonth: 2500,
      driver: 'John Doe',
      lastMaintenance: '2024-01-15',
      fuelEfficiency: 12.5,
      mileage: 45000,
      year: 2022,
      manufacturer: 'Toyota'
    },
    {
      vehicleRegNo: 'T 456 DEF',
      group: 'Logistics',
      status: 'available',
      model: 'Ford Transit',
      healthRate: 92,
      costPerMonth: 2800,
      driver: 'Jane Smith',
      lastMaintenance: '2024-01-20',
      fuelEfficiency: 11.8,
      mileage: 32000,
      year: 2023,
      manufacturer: 'Ford'
    },
    {
      vehicleRegNo: 'T 789 GHI',
      group: 'Transport',
      status: 'out of service',
      model: 'Mercedes Sprinter',
      healthRate: 45,
      costPerMonth: 3500,
      driver: 'Mike Johnson',
      lastMaintenance: '2024-01-10',
      fuelEfficiency: 10.2,
      mileage: 78000,
      year: 2021,
      manufacturer: 'Mercedes'
    },
    {
      vehicleRegNo: 'T 012 JKL',
      group: 'Logistics',
      status: 'available',
      model: 'Nissan NV350',
      healthRate: 88,
      costPerMonth: 2200,
      driver: 'Sarah Wilson',
      lastMaintenance: '2024-01-25',
      fuelEfficiency: 13.1,
      mileage: 28000,
      year: 2023,
      manufacturer: 'Nissan'
    },
    {
      vehicleRegNo: 'T 345 MNO',
      group: 'Transport',
      status: 'en route',
      model: 'Toyota Hiace',
      healthRate: 78,
      costPerMonth: 2400,
      driver: 'David Brown',
      lastMaintenance: '2024-01-12',
      fuelEfficiency: 11.9,
      mileage: 52000,
      year: 2022,
      manufacturer: 'Toyota'
    },
    {
      vehicleRegNo: 'T 678 PQR',
      group: 'Logistics',
      status: 'available',
      model: 'Ford Transit',
      healthRate: 95,
      costPerMonth: 2600,
      driver: 'Emily Davis',
      lastMaintenance: '2024-01-28',
      fuelEfficiency: 12.8,
      mileage: 18000,
      year: 2024,
      manufacturer: 'Ford'
    },
    {
      vehicleRegNo: 'T 901 STU',
      group: 'Transport',
      status: 'out of service',
      model: 'Mercedes Sprinter',
      healthRate: 32,
      costPerMonth: 3800,
      driver: 'Robert Wilson',
      lastMaintenance: '2024-01-05',
      fuelEfficiency: 9.5,
      mileage: 95000,
      year: 2020,
      manufacturer: 'Mercedes'
    },
    {
      vehicleRegNo: 'T 234 VWX',
      group: 'Logistics',
      status: 'en route',
      model: 'Nissan NV350',
      healthRate: 82,
      costPerMonth: 2300,
      driver: 'Lisa Anderson',
      lastMaintenance: '2024-01-18',
      fuelEfficiency: 12.2,
      mileage: 38000,
      year: 2022,
      manufacturer: 'Nissan'
    },
    {
      vehicleRegNo: 'T 567 YZA',
      group: 'Transport',
      status: 'available',
      model: 'Toyota Hiace',
      healthRate: 90,
      costPerMonth: 2500,
      driver: 'Tom Harris',
      lastMaintenance: '2024-01-22',
      fuelEfficiency: 12.7,
      mileage: 25000,
      year: 2023,
      manufacturer: 'Toyota'
    },
    {
      vehicleRegNo: 'T 890 BCD',
      group: 'Logistics',
      status: 'en route',
      model: 'Ford Transit',
      healthRate: 76,
      costPerMonth: 2700,
      driver: 'Anna Martinez',
      lastMaintenance: '2024-01-14',
      fuelEfficiency: 11.4,
      mileage: 48000,
      year: 2022,
      manufacturer: 'Ford'
    },
    {
      vehicleRegNo: 'T 123 EFG',
      group: 'Transport',
      status: 'available',
      model: 'Mercedes Sprinter',
      healthRate: 87,
      costPerMonth: 3200,
      driver: 'Carl Rodriguez',
      lastMaintenance: '2024-01-26',
      fuelEfficiency: 11.1,
      mileage: 35000,
      year: 2023,
      manufacturer: 'Mercedes'
    },
    {
      vehicleRegNo: 'T 456 HIJ',
      group: 'Logistics',
      status: 'out of service',
      model: 'Nissan NV350',
      healthRate: 28,
      costPerMonth: 2900,
      driver: 'Maria Garcia',
      lastMaintenance: '2024-01-08',
      fuelEfficiency: 8.9,
      mileage: 88000,
      year: 2021,
      manufacturer: 'Nissan'
    }
  ]