import { MaintenanceData } from '@/app/types';

export const maintenanceData: MaintenanceData[] = [
  {
    vehicleId: 'V001',
    vehicleRegNo: 'T 123 ABC',
    driver: 'Alice Johnson',
    healthScore: 85,
    lastServiceDate: '2024-05-15',
    nextServiceDate: '2024-07-15',
    serviceType: 'oil_change',
    status: 'good',
    estimatedCost: 150000,
    actualCost: 145000,
    serviceProvider: 'Toyota Dar es Salaam',
    mileage: 45000,
    downtime: 2,
    partsUsed: ['Oil Filter', 'Engine Oil 5W-30', 'Air Filter'],
    notes: 'Regular oil change service completed successfully',
    warrantyStatus: 'active',
    priority: 'low',
    completionDate: '2024-05-15',
    technician: 'John Mwamba',
    location: 'Dar es Salaam',
  },
  {
    vehicleId: 'V002',
    vehicleRegNo: 'T 456 DEF',
    driver: 'Brian Smith',
    healthScore: 45,
    lastServiceDate: '2024-04-20',
    nextServiceDate: '2024-06-20',
    serviceType: 'brakes',
    status: 'critical',
    estimatedCost: 350000,
    serviceProvider: 'Arusha Auto Services',
    mileage: 52000,
    downtime: 8,
    partsUsed: ['Brake Pads', 'Brake Fluid', 'Brake Discs'],
    notes: 'Brake system showing signs of wear, immediate attention required',
    warrantyStatus: 'expired',
    priority: 'urgent',
    technician: 'Peter Kimaro',
    location: 'Arusha',
  },
  {
    vehicleId: 'V003',
    vehicleRegNo: 'T 789 GHI',
    driver: 'Catherine Lee',
    healthScore: 72,
    lastServiceDate: '2024-05-10',
    nextServiceDate: '2024-06-10',
    serviceType: 'tires',
    status: 'due_soon',
    estimatedCost: 280000,
    serviceProvider: 'Mwanza Tire Center',
    mileage: 38000,
    downtime: 4,
    partsUsed: ['Tire Set', 'Wheel Alignment'],
    notes: 'Tires approaching replacement threshold',
    warrantyStatus: 'active',
    priority: 'medium',
    technician: 'Sarah Mwita',
    location: 'Mwanza',
  },
  {
    vehicleId: 'V004',
    vehicleRegNo: 'T 012 JKL',
    driver: 'Frank Wilson',
    healthScore: 92,
    lastServiceDate: '2024-05-20',
    nextServiceDate: '2024-08-20',
    serviceType: 'inspection',
    status: 'good',
    estimatedCost: 80000,
    actualCost: 75000,
    serviceProvider: 'Dodoma Vehicle Inspection',
    mileage: 28000,
    downtime: 1,
    partsUsed: ['Inspection Certificate'],
    notes: 'Annual inspection passed with flying colors',
    warrantyStatus: 'active',
    priority: 'low',
    completionDate: '2024-05-20',
    technician: 'David Mwenda',
    location: 'Dodoma',
  },
  {
    vehicleId: 'V005',
    vehicleRegNo: 'T 345 MNO',
    driver: 'Grace Taylor',
    healthScore: 68,
    lastServiceDate: '2024-04-25',
    nextServiceDate: '2024-06-25',
    serviceType: 'filter_change',
    status: 'due_soon',
    estimatedCost: 120000,
    serviceProvider: 'Morogoro Auto Parts',
    mileage: 42000,
    downtime: 3,
    partsUsed: ['Fuel Filter', 'Air Filter', 'Oil Filter'],
    notes: 'Filters due for replacement',
    warrantyStatus: 'active',
    priority: 'medium',
    technician: 'Michael Kipanga',
    location: 'Morogoro',
  },
  {
    vehicleId: 'V006',
    vehicleRegNo: 'T 678 PQR',
    driver: 'Iris Davis',
    healthScore: 35,
    lastServiceDate: '2024-03-15',
    nextServiceDate: '2024-05-15',
    serviceType: 'repair',
    status: 'overdue',
    estimatedCost: 450000,
    serviceProvider: 'Mbeya Engine Works',
    mileage: 65000,
    downtime: 12,
    partsUsed: ['Engine Parts', 'Gaskets', 'Belts'],
    notes: 'Engine overheating issues, major repair needed',
    warrantyStatus: 'expired',
    priority: 'high',
    technician: 'Robert Mwakasege',
    location: 'Mbeya',
  },
  {
    vehicleId: 'V007',
    vehicleRegNo: 'T 901 STU',
    driver: 'Jack Miller',
    healthScore: 88,
    lastServiceDate: '2024-05-18',
    nextServiceDate: '2024-08-18',
    serviceType: 'battery',
    status: 'good',
    estimatedCost: 180000,
    actualCost: 175000,
    serviceProvider: 'Iringa Battery Center',
    mileage: 32000,
    downtime: 2,
    partsUsed: ['Battery', 'Terminal Cleaner'],
    notes: 'Battery replacement completed',
    warrantyStatus: 'active',
    priority: 'low',
    completionDate: '2024-05-18',
    technician: 'Anna Mwambene',
    location: 'Iringa',
  },
  {
    vehicleId: 'V008',
    vehicleRegNo: 'T 234 VWX',
    driver: 'Kate Anderson',
    healthScore: 55,
    lastServiceDate: '2024-04-30',
    nextServiceDate: '2024-06-30',
    serviceType: 'cooling_system',
    status: 'critical',
    estimatedCost: 220000,
    serviceProvider: 'Songea Cooling Systems',
    mileage: 48000,
    downtime: 6,
    partsUsed: ['Radiator', 'Coolant', 'Thermostat'],
    notes: 'Cooling system failure, vehicle overheating',
    warrantyStatus: 'active',
    priority: 'urgent',
    technician: 'William Mwakalukwa',
    location: 'Songea',
  },
  {
    vehicleId: 'V009',
    vehicleRegNo: 'T 567 YZA',
    driver: 'Liam Thompson',
    healthScore: 95,
    lastServiceDate: '2024-05-22',
    nextServiceDate: '2024-08-22',
    serviceType: 'oil_change',
    status: 'good',
    estimatedCost: 140000,
    actualCost: 135000,
    serviceProvider: 'Kigoma Auto Services',
    mileage: 25000,
    downtime: 1,
    partsUsed: ['Oil Filter', 'Synthetic Oil', 'Air Filter'],
    notes: 'Synthetic oil change, excellent condition',
    warrantyStatus: 'active',
    priority: 'low',
    completionDate: '2024-05-22',
    technician: 'Grace Mwakatundu',
    location: 'Kigoma',
  },
  {
    vehicleId: 'V010',
    vehicleRegNo: 'T 890 BCD',
    driver: 'Noah Martinez',
    healthScore: 78,
    lastServiceDate: '2024-05-12',
    nextServiceDate: '2024-07-12',
    serviceType: 'brakes',
    status: 'due_soon',
    estimatedCost: 320000,
    serviceProvider: 'Tabora Brake Specialists',
    mileage: 41000,
    downtime: 5,
    partsUsed: ['Brake Pads', 'Brake Fluid'],
    notes: 'Brake pads showing wear, scheduled replacement',
    warrantyStatus: 'active',
    priority: 'medium',
    technician: 'Joseph Mwakalenga',
    location: 'Tabora',
  },
  {
    vehicleId: 'V011',
    vehicleRegNo: 'T 123 EFG',
    driver: 'Olivia Robinson',
    healthScore: 42,
    lastServiceDate: '2024-04-05',
    nextServiceDate: '2024-06-05',
    serviceType: 'repair',
    status: 'overdue',
    estimatedCost: 380000,
    serviceProvider: 'Bukoba Vehicle Repair',
    mileage: 58000,
    downtime: 10,
    partsUsed: ['Transmission Parts', 'Clutch', 'Flywheel'],
    notes: 'Transmission issues, clutch replacement needed',
    warrantyStatus: 'expired',
    priority: 'high',
    technician: 'Daniel Mwakatundu',
    location: 'Bukoba',
  },
  {
    vehicleId: 'V012',
    vehicleRegNo: 'T 345 QRS',
    driver: 'Tina Hall',
    healthScore: 82,
    lastServiceDate: '2024-05-25',
    nextServiceDate: '2024-08-25',
    serviceType: 'inspection',
    status: 'good',
    estimatedCost: 85000,
    actualCost: 80000,
    serviceProvider: 'Lindi Vehicle Inspection',
    mileage: 29000,
    downtime: 1,
    partsUsed: ['Inspection Certificate'],
    notes: 'Routine inspection completed successfully',
    warrantyStatus: 'active',
    priority: 'low',
    completionDate: '2024-05-25',
    technician: 'Maria Mwambene',
    location: 'Lindi',
  },
]; 