import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FleetCo",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< Updated upstream
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
=======
      <body className={`${sourceSans.className} antialiased`} suppressHydrationWarning={true}>
>>>>>>> Stashed changes
        <Providers>
          {children}
          <Toaster richColors theme="dark" />
        </Providers>
      </body>
    </html>
  );
}
